# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('foundation', models.IntegerField(verbose_name=b'4')),
                ('city', models.CharField(max_length=25)),
                ('stadium', models.CharField(max_length=25)),
                ('coach', models.CharField(max_length=25)),
                ('capacity', models.IntegerField(verbose_name=b'6')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=25)),
                ('nacionality', models.CharField(max_length=3)),
                ('age', models.IntegerField(verbose_name=b'2')),
                ('heigh', models.IntegerField(verbose_name=b'3')),
                ('position', models.CharField(max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
